# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


# muscles = Muscle.create([name: "Abs", image_url: ""])
exercise = Exercise.create([name: "Cable Crunch", description: "", equipment: "", muscle_primary: "5", muscle_secondary: ""])
exercise = Exercise.create([name: "Hanging Leg Raise", description: "", equipment: "", muscle_primary: "5", muscle_secondary: ""])
exercise = Exercise.create([name: "Windshield Wipers", description: "", equipment: "", muscle_primary: "5", muscle_secondary: ""])
# muscles = Muscle.create([name: "Biceps", image_url: ""])
exercise = Exercise.create([name: "Barbell Curl", description: "", equipment: "", muscle_primary: "6", muscle_secondary: ""])
exercise = Exercise.create([name: "Cable Curl", description: "", equipment: "", muscle_primary: "6", muscle_secondary: ""])
exercise = Exercise.create([name: "incline Dumbbell curl", description: "", equipment: "", muscle_primary: "6", muscle_secondary: ""])
# muscles = Muscle.create([name: "Chest", image_url: ""])
exercise = Exercise.create([name: "Incline Bench Press", description: "", equipment: "", muscle_primary: "7", muscle_secondary: "15"])
exercise = Exercise.create([name: "Incline Dumbbell Press", description: "", equipment: "", muscle_primary: "7", muscle_secondary: "15"])
exercise = Exercise.create([name: "Dumbbell Press", description: "", equipment: "", muscle_primary: "7", muscle_secondary: ""])
exercise = Exercise.create([name: "Cable Fly", description: "", equipment: "", muscle_primary: "7", muscle_secondary: ""])
exercise = Exercise.create([name: "Cable Incline Fly", description: "", equipment: "", muscle_primary: "7", muscle_secondary: ""])
exercise = Exercise.create([name: "Prayer", description: "", equipment: "", muscle_primary: "7", muscle_secondary: ""])
exercise = Exercise.create([name: "Isolation", description: "", equipment: "", muscle_primary: "7", muscle_secondary: ""])
# muscles = Muscle.create([name: "Triceps", image_url: ""])
exercise = Exercise.create([name: "Close-Grip Bench ", description: "", equipment: "", muscle_primary: "8", muscle_secondary: "7"])
exercise = Exercise.create([name: "Cable Rope Tricep Pushdown", description: "", equipment: "", muscle_primary: "8", muscle_secondary: ""])
exercise = Exercise.create([name: "Lying Triceps Extension", description: "", equipment: "", muscle_primary: "8", muscle_secondary: ""])
exercise = Exercise.create([name: "Tricep Dips", description: "", equipment: "", muscle_primary: "8", muscle_secondary: "7"])
exercise = Exercise.create([name: "Cable Tricep Extension", description: "", equipment: "", muscle_primary: "8", muscle_secondary: ""])
# muscles = Muscle.create([name: "Traps", image_url: ""])
exercise = Exercise.create([name: "Barbell Shrug", description: "", equipment: "", muscle_primary: "9", muscle_secondary: ""])
exercise = Exercise.create([name: "Dumbbell Shrug", description: "", equipment: "", muscle_primary: "9", muscle_secondary: ""])
exercise = Exercise.create([name: "Barbell Upright Row", description: "", equipment: "", muscle_primary: "9", muscle_secondary: ""])
# muscles = Muscle.create([name: "Quadriceps", image_url: ""])
exercise = Exercise.create([name: "Leg Press", description: "", equipment: "", muscle_primary: "10", muscle_secondary: "13"])
exercise = Exercise.create([name: "Leg Extensions", description: "", equipment: "", muscle_primary: "10", muscle_secondary: ""])
exercise = Exercise.create([name: "Barbell Back Squat", description: "", equipment: "", muscle_primary: "10", muscle_secondary: "13"])
exercise = Exercise.create([name: "Diagonal Walking Lunges", description: "", equipment: "", muscle_primary: "10", muscle_secondary: "14"])
# muscles = Muscle.create([name: "Lats", image_url: ""])
exercise = Exercise.create([name: "Barbell Row", description: "", equipment: "", muscle_primary: "11", muscle_secondary: ""])
exercise = Exercise.create([name: "Landmine Row", description: "", equipment: "", muscle_primary: "11", muscle_secondary: ""])
exercise = Exercise.create([name: "Straight Arm Lat Pushdown", description: "", equipment: "", muscle_primary: "11", muscle_secondary: ""])
exercise = Exercise.create([name: "Cable Row", description: "", equipment: "", muscle_primary: "11", muscle_secondary: ""])
exercise = Exercise.create([name: "One arm Lat Pulldown", description: "", equipment: "", muscle_primary: "11", muscle_secondary: ""])
# muscles = Muscle.create([name: "Calves", image_url: ""])
exercise = Exercise.create([name: "Seated Calf Raise", description: "", equipment: "", muscle_primary: "12", muscle_secondary: ""])
# muscles = Muscle.create([name: "Glutes", image_url: ""])
exercise = Exercise.create([name: "Hip Thrusts", description: "", equipment: "", muscle_primary: "13", muscle_secondary: ""])
# muscles = Muscle.create([name: "Hamstrings", image_url: ""])
exercise = Exercise.create([name: "Leg Curls", description: "", equipment: "", muscle_primary: "14", muscle_secondary: ""])
# muscles = Muscle.create([name: "Shoulder", image_url: ""])
exercise = Exercise.create([name: "Barbell Overhead Shoulder Press", description: "", equipment: "", muscle_primary: "15", muscle_secondary: ""])
exercise = Exercise.create([name: "Seated Dumbbell Shoulder Press", description: "", equipment: "", muscle_primary: "15", muscle_secondary: ""])
exercise = Exercise.create([name: "Front Raise", description: "", equipment: "", muscle_primary: "15", muscle_secondary: ""])
exercise = Exercise.create([name: "Bent-Over Dumbbell Lateral Raise", description: "", equipment: "", muscle_primary: "15", muscle_secondary: ""])
exercise = Exercise.create([name: "Dumbbell Lateral Raise", description: "", equipment: "", muscle_primary: "15", muscle_secondary: ""])
exercise = Exercise.create([name: "Dumbbell Rear Fly", description: "", equipment: "", muscle_primary: "15", muscle_secondary: ""])
# muscles = Muscle.create([name: "Forearms", image_url: ""])
exercise = Exercise.create([name: "Reverse Curl", description: "", equipment: "", muscle_primary: "16", muscle_secondary: ""])


